name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - ghidra-version: "12.0"
            ghidra-date: "20251205"

          - ghidra-version: "12.0.4"
            ghidra-date: "20260303"

          - ghidra-version: "12.1"
            ghidra-date: "20260513"

    steps:
      - uses: actions/checkout@v7

      - name: Build Ghidra ${{ matrix.ghidra-version }}
        uses: ./.github/actions/build-ghidra
        with:
          ghidra-version: ${{ matrix.ghidra-version }}
          ghidra-date: ${{ matrix.ghidra-date }}
          ghidra-download-dir: ${{ runner.temp }}/ghidra-${{ matrix.ghidra-version }}
          output-dir: release

      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          name: plugin-${{ matrix.ghidra-version }}
          path: release


  release:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v5
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          generate_release_notes: true
          files: artifacts/**/*